version: "3"
services:
  circle-swipe-engine:
    image: circle-swipe-engine
    build:
        context: .
        dockerfile: Dockerfile
    command: npm run start
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
    env_file:
      - .env